from retinanalysis.config.settings import H5_DIR, QUERY_DIR, ANALYSIS_DIR
from retinanalysis._database import schema

import numpy as np
import datajoint as dj
import os
import pandas as pd
import json
import re
import warnings
from tqdm.auto import tqdm
from IPython.display import display
import h5py
from typing import List, Optional


# Default keywords used to drop "not a real cell type" labels (catch-all / low-confidence
# classifier bins) from the auto-detected cell type list in plot_mosaics_for_datasets. Case
# insensitive. "nc" is matched as a whole token (optionally followed by digits, e.g. "nc17")
# rather than as a plain substring, to avoid accidentally matching inside an unrelated type
# name. The rest are matched as plain substrings so they also catch compound labels like
# "OnLarge" or "BigMas". Override by passing exclude_cell_type_keywords= to
# plot_mosaics_for_datasets, or edit this list if your lab's junk-bin vocabulary differs.
DEFAULT_EXCLUDED_CELL_TYPE_KEYWORDS = ["unknown", "nc", "large", "big", "huge", "weak"]


def _should_exclude_cell_type(cell_type: str, exclude_keywords: List[str]) -> bool:
    """
    Returns True if cell_type looks like a catch-all/low-confidence label that should be
    dropped from an auto-detected cell type list, based on exclude_keywords.
    """
    ct_lower = str(cell_type).lower()
    for kw in exclude_keywords:
        kw_lower = kw.lower()
        if kw_lower == "nc":
            if re.search(r"(?<![a-z])nc\d*(?![a-z])", ct_lower):
                return True
        elif kw_lower in ct_lower:
            return True
    return False


def plot_mosaics_for_datasets(
    df_exp_search: pd.DataFrame,
    cell_types: Optional[List[str]] = None,
    preferred_typing_file: Optional[str] = None,
    exclude_cell_type_keywords: Optional[List[str]] = None,
    verbose: bool = False,
    **kwargs,
):
    """
    Function for plotting mosaics across datasets listed in an experiment search dataframe.

    CHANGED 2026-07-28 (Claude, per yas): this function used to resolve, for every row of
    df_exp_search, the "nearest" noise chunk by time-distance and would silently substitute
    a different chunk if the requested one failed to load (e.g. due to a missing RTMP tag).
    Because df_exp_search can contain several rows per experiment (one per epoch block), many
    rows would resolve to the very same fallback chunk, so the same mosaic could get plotted
    two or three times in a row. It also defaulted cell_types to a hardcoded, project-specific
    list (['OnP','OffP','OnM','OffM']) that didn't match this lab's actual classification
    labels.

    New behavior:
    - Every unique (exp_name, chunk_name) pair present in df_exp_search is attempted at most
      once. There is no cross-chunk substitution: if a chunk fails to load, it is skipped
      (with a printed message) and the next chunk for that same experiment is tried. This is
      what actually prevents duplicate mosaics, instead of masking the problem by only ever
      plotting the first chunk found.
    - A chunk is only plotted if it has at least one classification/typing file (any file in
      analysis_chunk.typing_files whose name contains "classification", case-insensitive).
      Chunks without a classification file are skipped silently (they're not failures, just
      not usable for mosaics). If NONE of an experiment's chunks have a classification file,
      that is reported once for the whole experiment.
    - If a chunk has more than one classification file (i.e. more than one person typed it),
      a mosaic is plotted for each one, unless preferred_typing_file is given and present.
    - Each plotted mosaic's title reports the experiment, chunk, NDF (light level) pulled from
      the 'NDF' column of df_exp_search, and which classification file was used.
    - cell_types now defaults to None. UPDATED 2026-07-28 (Claude, per yas): when None, this
      no longer means "plot literally every type string found" -- it means "auto-detect every
      type present, then drop catch-all/low-confidence labels" (see exclude_cell_type_keywords
      below). Pass an explicit cell_types=[...] list yourself to bypass this filtering
      entirely and plot exactly those types.
    - Console output is now much shorter: chunk loading uses a single tqdm progress bar
      instead of printing "Loading VCD..." / "VCD loaded with N cells" for every chunk, so
      you don't have to scroll past a wall of text to reach the actual mosaic figures. Set
      verbose=True to get the old per-chunk loading detail back (useful for debugging).

    This redesign is scoped to this function only. Chunk selection used elsewhere (e.g.
    create_mea_pipeline / single-experiment setup, or matching a noise chunk to a non-noise
    protocol like PresentImages) is untouched.

    Parameters:
    df_exp_search (pandas.DataFrame): an exp_search dataframe generated by the
    get_datasets_from_protocol_names function. Must contain 'exp_name' and 'chunk_name'
    columns; 'NDF' and 'block_id' are used if present (NDF for labeling, block_id to sort
    chunks chronologically within an experiment).

    cell_types (Optional[List[str]]): An explicit list of cell types to plot. Default None,
    which auto-detects every cell type present in the classification file being plotted and
    then removes catch-all/low-confidence labels per exclude_cell_type_keywords. If you pass
    your own list, it is used exactly as given -- exclude_cell_type_keywords is NOT applied,
    since you've already told the function exactly what you want.

    preferred_typing_file (str): The name of a preferred cell typing .txt file. If a given
    chunk doesn't have this file, all of that chunk's available classification file(s) are
    plotted instead (with a printed note), rather than silently falling back to just the
    first one.

    exclude_cell_type_keywords (Optional[List[str]]): Keywords (case-insensitive) used to
    drop catch-all/low-confidence labels from the auto-detected cell type list when
    cell_types is None. Default is DEFAULT_EXCLUDED_CELL_TYPE_KEYWORDS = ['unknown', 'nc',
    'large', 'big', 'huge', 'weak']. 'nc' is matched as a whole token (so it also catches
    'nc17', but won't match inside an unrelated word); the rest are matched as substrings (so
    'large' also catches 'OnLarge'). Define your own list and pass it in if this lab's set of
    junk-bin labels changes -- e.g. at the top of a notebook:
        EXCLUDE_CELL_TYPES = ['unknown', 'nc', 'large', 'big', 'huge', 'weak']
        ra.plot_mosaics_for_datasets(exp_search, exclude_cell_type_keywords=EXCLUDE_CELL_TYPES, ...)
    If, after exclusion, a chunk has zero cell types left to plot, that chunk/typing_file
    combination is skipped (reported once) rather than producing an empty figure.

    verbose (bool): If True, restores the old per-chunk "Loading VCD..." console output.
    Default False (a single compact progress bar is shown instead).

    **kwargs: key value pairs of params fed into the analysis_chunk.plot_rfs function such as
    b_zoom and minimum_n.

    Returns:
    ls_rf_axes (List[Axes]): A list of axes, one entry per (experiment, chunk, classification
    file) that was actually plotted.
    """

    required_cols = {"exp_name", "chunk_name"}
    missing_cols = required_cols - set(df_exp_search.columns)
    if missing_cols:
        raise ValueError(
            f"df_exp_search is missing required column(s): {sorted(missing_cols)}. "
            "Use get_datasets_from_protocol_names() to build a compatible dataframe."
        )

    from retinanalysis.classes.analysis_chunk import AnalysisChunk

    exclude_keywords = (
        DEFAULT_EXCLUDED_CELL_TYPE_KEYWORDS
        if exclude_cell_type_keywords is None
        else exclude_cell_type_keywords
    )

    ls_rf_axes = []

    # Build the full (exp_name, chunk_name, NDF) candidate list up front so the progress bar
    # below reflects real work (one tick per chunk actually attempted), not one tick per
    # experiment regardless of how many chunks it has.
    ls_candidates = []
    for exp in df_exp_search["exp_name"].unique():
        df_exp_rows = df_exp_search.query("exp_name == @exp")

        # One row per unique chunk in this experiment. Sorting by block_id (if available)
        # keeps plotting order chronological instead of depending on row order in the input.
        dedup_cols = [
            c for c in ["chunk_name", "NDF", "block_id"] if c in df_exp_rows.columns
        ]
        df_chunks = df_exp_rows.drop_duplicates(subset="chunk_name")[dedup_cols]
        if "block_id" in df_chunks.columns:
            df_chunks = df_chunks.sort_values("block_id")

        for _, chunk_row in df_chunks.iterrows():
            ls_candidates.append((exp, chunk_row))

    classified_exps = set()
    checked_exps = set()

    pbar = tqdm(ls_candidates, desc="Checking noise chunks for classification files")
    for exp, chunk_row in pbar:
        chunk_name = chunk_row["chunk_name"]
        checked_exps.add(exp)
        ndf = chunk_row["NDF"] if "NDF" in chunk_row.index else None
        ndf_label = f"NDF {ndf}" if ndf is not None and not pd.isna(ndf) else "NDF unknown"
        pbar.set_postfix_str(f"{exp} {chunk_name}")

        try:
            analysis_chunk = AnalysisChunk(
                exp,
                chunk_name,
                b_load_spatial_maps=False,
                include_ei=False,
                include_neurons=False,
                verbose=verbose,
            )
        except Exception as e:
            tqdm.write(
                f"Could not load chunk {chunk_name} for {exp} ({ndf_label}), skipping. Error: {e}"
            )
            continue

        # Only treat files that look like classification/typing files as usable. This is
        # a local filter (doesn't change AnalysisChunk.typing_files itself) since typing
        # file naming isn't fully consistent, but always contains "classification".
        classification_files = [
            f for f in analysis_chunk.typing_files if "classification" in f.lower()
        ]

        if not classification_files:
            continue

        classified_exps.add(exp)

        if preferred_typing_file is not None and preferred_typing_file in classification_files:
            files_to_plot = [preferred_typing_file]
        else:
            if preferred_typing_file is not None:
                tqdm.write(
                    f"{preferred_typing_file} not found for {exp} {chunk_name}, plotting "
                    f"all available classification file(s) instead: {classification_files}"
                )
            files_to_plot = classification_files

        for typing_file in files_to_plot:
            plot_cell_types = cell_types

            if plot_cell_types is None:
                # Auto-detect: pull every type actually present in this typing file, then
                # drop catch-all/low-confidence labels (see exclude_cell_type_keywords).
                typing_file_idx = analysis_chunk.typing_files.index(typing_file)
                all_types_present = sorted(
                    analysis_chunk.df_cell_params[f"typing_file_{typing_file_idx}"].unique()
                )
                plot_cell_types = [
                    ct for ct in all_types_present
                    if not _should_exclude_cell_type(ct, exclude_keywords)
                ]

                if not plot_cell_types:
                    tqdm.write(
                        f"No cell types of interest (after excluding {exclude_keywords}) for "
                        f"{exp} {chunk_name} ({typing_file}, {ndf_label}), skipping."
                    )
                    continue

            rf_axes = analysis_chunk.plot_rfs(
                cell_types=plot_cell_types, typing_file=typing_file, **kwargs
            )

            if rf_axes is None or len(rf_axes) == 0:
                tqdm.write(f"No RFs for {exp} {chunk_name} ({typing_file}, {ndf_label})")
                continue

            fig = rf_axes[0].get_figure()
            fig.suptitle(f"{exp} {chunk_name} | {ndf_label} | {typing_file}")
            ls_rf_axes.append(rf_axes)

    for exp in checked_exps - classified_exps:
        tqdm.write(f"No classification files found for any noise chunk in {exp}")

    return ls_rf_axes


def djconnect(
    host_address: str = "127.0.0.1",
    user: str = "root",
    password: str = "simple",
    port: int = 3306,
):
    """
    Deprecated helper for connecting to a local DataJoint database container.

    DataJoint configuration is now applied lazily when the schema module is
    loaded. Prefer configuring DataJoint through ``datajoint.json`` or by
    setting ``dj.config`` before calling database-backed retinanalysis helpers.

    This function is kept as a temporary compatibility shim for old notebooks.
    It still attempts an immediate connection when called explicitly.
    """

    warnings.warn(
        "retinanalysis.djconnect() is deprecated. Configure DataJoint via "
        "datajoint.json or dj.config before calling database-backed helpers.",
        DeprecationWarning,
        stacklevel=2,
    )

    try:
        dj.config["database.host"] = host_address
        dj.config["database.port"] = port
        dj.config["database.user"] = user
        dj.config["database.password"] = password
        return dj.conn()
    except Exception as e:
        print(f"Could not connect to DataJoint database: {e}")
        return None


def populate_ndf_column(df_exp_summary):
    """
    Helper function for pulling the NDF value (filter wheel ND being used) from
    the first epoch of each epoch block run on a given day, and adding it to the
    NDF column of the experiment summary dataframe.

    Parameters:
    df_exp_summary (pandas DataFrame): experiment summary dataframe from
    get_exp_summary() function.

    NOTE: This is only a helper function used inside that function, nothing more.

    Returns:
    df_exp_summary (pandas DataFrame): returns the modified dataframe with the
    NDF column added.
    """

    df_exp_summary["NDF"] = np.nan
    for bid in df_exp_summary["block_id"].values:
        ep_q = schema.Epoch() & f"parent_id={bid}"
        if len(ep_q) == 0:
            print(f"No epochs found for block {bid}")
            continue
        ep_id = ep_q.to_arrays("id")[0]
        params = (schema.Epoch() & f"id={ep_id}").fetch1("parameters")
        if "NDF" in params.keys():
            df_exp_summary.loc[df_exp_summary["block_id"] == bid, "NDF"] = params["NDF"]
        # else:
        # print(f'NDF parameter not found for block_id {bid}')
    return df_exp_summary


def get_exp_summary(exp_name: str) -> Optional[pd.DataFrame]:
    """Generate an experiment summary dataframe while tolerating newer sorting layouts.

    This helper now keeps working even when chunk IDs or sorting chunk rows are missing,
    which is important for the newer data-directory-based structure where chunk folders
    may not exist in the old form.

    Parameters:
    exp_name (str): The experiment name to summarize (i.e. '20251008C')

    Returns:
    df_exp_summary (pandas DataFrame): A dataframe containing a list of protocols
    run on that experiment day, their mount, their timing, their sorting chunk, and
    their datafile directory.
    """
    # Adapted to tolerate missing SortingChunk rows and newer data-directory layouts.

    exp_ids = (schema.Experiment() & f'exp_name="{exp_name}"').to_arrays("id")
    if len(exp_ids) == 0:
        print(f'Experiment "{exp_name}" not found!')
        return None
    exp_id = exp_ids[0]
    is_mea = (schema.Experiment() & f"id={exp_id}").fetch1("is_mea")

    epoch_group_query = schema.EpochGroup() & f"experiment_id={exp_id}"
    epoch_group_query = epoch_group_query.proj(
        "experiment_id",
        group_label="label",
        group_id="id",
        cell_id="parent_id",
        group_properties="properties",
    )

    # For single cell, pull out recording technique and pipette solution
    if not is_mea:
        epoch_group_query = epoch_group_query.proj(
            ...,
            recording_technique="group_properties->>'$.recordingTechnique'",
            pipette_solution="group_properties->>'$.pipetteSolution'",
        )

    cell_query = schema.Cell.proj(
        prep_id="parent_id",
        cell_id="id",
        cell_label="label",
        cell_properties="properties",
    )  # type: ignore

    prep_query = schema.Preparation.proj(prep_label="label", prep_id="id")  # type: ignore

    epoch_group_query = epoch_group_query * cell_query * prep_query
    epoch_block_query = schema.EpochBlock.proj(
        "chunk_id",
        "protocol_id",
        "data_dir",
        "start_time",  # type: ignore
        "end_time",
        group_id="parent_id",
        block_id="id",
    )

    epoch_block_query = epoch_group_query * epoch_block_query

    # If MEA experiment, get sorting chunk information when available.
    # The newer sorted-data layout may not populate SortingChunk rows in the old way,
    # so fall back to empty chunk metadata rather than failing the notebook summary.
    if is_mea:
        sorting_chunk_query = schema.SortingChunk() & f"experiment_id={exp_id}"
        sorting_chunk_query = sorting_chunk_query.proj("chunk_name", chunk_id="id")
        if len(sorting_chunk_query) > 0:
            epoch_block_query = epoch_block_query * sorting_chunk_query
        else:
            epoch_block_query = epoch_block_query.proj(
                ...,
                chunk_name="" ,
                chunk_id="",
            )
    protocol_query = epoch_block_query * schema.Protocol.proj(..., protocol_name="name")  # type: ignore

    df_exp_summary = protocol_query.to_pandas().reset_index()
    df_exp_summary = df_exp_summary.sort_values("start_time").reset_index()
    if len(df_exp_summary) == 0:
        print(f"No data found for experiment {exp_name}; returning empty summary.")
        return pd.DataFrame(columns=[
            "exp_name",
            "prep_label",
            "datafile_name",
            "group_label",
            "NDF",
            "chunk_name",
            "protocol_name",
            "duration_minutes",
            "minutes_since_start",
            "start_time",
            "end_time",
            "data_dir",
            "experiment_id",
            "prep_id",
            "group_id",
            "block_id",
            "chunk_id",
            "protocol_id",
        ])

    # Check that end_time and start_time are in datetime format
    if not pd.api.types.is_datetime64_any_dtype(df_exp_summary["start_time"]):
        print("Converting 'start_time' to datetime format.")
        df_exp_summary["start_time"] = pd.to_datetime(
            df_exp_summary["start_time"], errors="coerce"
        )
    if not pd.api.types.is_datetime64_any_dtype(df_exp_summary["end_time"]):
        print("Converting 'end_time' to datetime format.")
        df_exp_summary["end_time"] = pd.to_datetime(
            df_exp_summary["end_time"], errors="coerce"
        )
    # Add column of minutes_since_start
    df_exp_summary["minutes_since_start"] = (
        df_exp_summary["end_time"] - df_exp_summary["start_time"].min()
    ).dt.total_seconds() / 60
    df_exp_summary["minutes_since_start"] = df_exp_summary["minutes_since_start"].round(
        2
    )
    # Add delta_minutes which gives derivative along rows
    df_exp_summary["duration_minutes"] = (
        df_exp_summary["end_time"] - df_exp_summary["start_time"]
    ).dt.total_seconds() / 60
    df_exp_summary["duration_minutes"] = df_exp_summary["duration_minutes"].round(2)

    df_exp_summary["exp_name"] = exp_name

    df_exp_summary = populate_ndf_column(df_exp_summary)

    if is_mea:
        df_exp_summary["datafile_name"] = df_exp_summary["data_dir"].apply(
            lambda x: os.path.split(x)[-1]
        )

        # Order columns.
        ls_order = [
            "exp_name",
            "prep_label",
            "datafile_name",
            "group_label",
            "NDF",
            "chunk_name",
            "protocol_name",
            "duration_minutes",
            "minutes_since_start",
            "start_time",
            "end_time",
            "data_dir",
            "experiment_id",
            "prep_id",
            "group_id",
            "block_id",
            "chunk_id",
            "protocol_id",
        ]
    else:
        # Add cell type from cell_properties dict w/ key 'type'
        df_exp_summary["cell_type"] = df_exp_summary["cell_properties"].apply(
            lambda x: x.get("type", "Unknown")
        )
        ls_order = [
            "exp_name",
            "prep_label",
            "recording_technique",
            "pipette_solution",
            "cell_id",
            "cell_label",
            "cell_type",
            "NDF",
            "protocol_name",
            "duration_minutes",
            "minutes_since_start",
            "start_time",
            "end_time",
            "cell_properties",
            "group_label",
            "experiment_id",
            "prep_id",
            "group_id",
            "block_id",
            "protocol_id",
        ]
    df_exp_summary = df_exp_summary[ls_order]

    return df_exp_summary


def get_block_id_from_datafile(exp_name: str, datafile_name: str):
    """
    Function for grabbing the block_id from a given experiment and datafile name.

    Parameters:
    exp_name (str): name of experiment to query (i.e. '20251008C')

    datafile_name (str): datafile name for protocol of interest (i.e. 'data008')

    Returns:
    block_id (int): the integer block id for this experiment and datafile
    """

    exp_id = (schema.Experiment() & f'exp_name="{exp_name}"').fetch1("id")
    epoch_block_query = schema.EpochBlock() & f"experiment_id={exp_id}"

    df_epoch_block = epoch_block_query.to_pandas().reset_index()
    df_epoch_block["datafile_name"] = df_epoch_block["data_dir"].apply(
        lambda x: os.path.split(x)[-1]
    )

    block_id = df_epoch_block.query("datafile_name == @datafile_name")["id"].values[0]
    return block_id


def search_protocol(str_search: str, verbose: bool = True):
    """Search for Symphony protocols by name.

    Parameters:
    str_search (str): A substring contained somewhere inside the protocol name.

    Returns:
    matches (List[str]): A list of matching protocol names.
    """

    str_search = str_search.lower()
    protocols = schema.Protocol().to_arrays("name")
    protocols = np.unique(protocols)
    matches = []
    for p in protocols:
        if str_search in p.lower():
            matches.append(p)
    matches = np.array(matches)

    if verbose:
        print(f'\nFound {len(matches)} protocols matching "{str_search}":')
        print(matches)
    return matches


def get_datasets_from_protocol_names(
    ls_protocol_names: str | List[str],
    b_exact_match: bool = False,
    verbose: bool = True,
):
    """
    Function for pulling dataset information for all experiments that contain a particular protocol.

    Parameters:
    ls_protocol_names (str or List[str]): A list of protocol names (or a single string) for the function
    to search. The basic search is a lowercase includes, so a piece of a protocol name is all that's needed.

    b_exact_match (bool): Boolean value that indicates if the protocol must be an exact match to the given
    string or list of strings.

    verbose (bool): Boolean value for printing out status information to console

    Returns:
    df_exp_search (pandas DataFrame): A pandas dataframe containing information about all datasets that
    contain the given protocols.
    """

    # TODO pull available algorithm names from CellTypeFile
    if isinstance(ls_protocol_names, str):
        ls_protocol_names = [ls_protocol_names]

    if b_exact_match:
        found_protocols = ls_protocol_names
    else:
        found_protocols = []
        for protocol in ls_protocol_names:
            found_protocols += list(search_protocol(protocol, verbose=verbose))

    # Query protocol table
    protocol_query = schema.Protocol() & [
        f'name="{protocol}"' for protocol in found_protocols
    ]
    protocol_ids = protocol_query.to_arrays("protocol_id")
    protocol_query = protocol_query.proj("protocol_id", protocol_name="name")

    # Query EpochBlock with these protocol IDs, get associated experiment IDs
    # WARNING: do not use EpochGroup ever for protocol_id queries bc of the "no_group_protocol" situation.
    # Thank you to @DRezeanu for pointing this out.
    epoch_block_query = schema.EpochBlock() & [
        f"protocol_id={p_id}" for p_id in protocol_ids
    ]
    experiment_ids = epoch_block_query.to_arrays("experiment_id")
    experiment_ids = np.unique(experiment_ids)

    # Join Experiment, EpochGroup, Protocol
    exp_query = schema.Experiment() & [f"id={ex_id}" for ex_id in experiment_ids]
    exp_query = exp_query.proj("exp_name", "is_mea", experiment_id="id")
    epoch_group_query = schema.EpochGroup() & [
        f"experiment_id={ex_id}" for ex_id in experiment_ids
    ]
    epoch_group_query = epoch_group_query.proj(
        "experiment_id", group_label="label", group_id="id"
    )
    epoch_group_query = protocol_query * epoch_group_query
    epoch_group_query = epoch_group_query * exp_query

    # Join with EpochBlock
    epoch_block_query = epoch_group_query * schema.EpochBlock.proj(
        "chunk_id",
        "data_dir",
        "protocol_id",  # type: ignore
        group_id="parent_id",
        block_id="id",
    )

    # Join with SortingChunk and fetch
    sorting_chunk_query = schema.SortingChunk.proj("chunk_name", chunk_id="id")  # type: ignore
    epoch_block_query = epoch_block_query * sorting_chunk_query
    df_exp_search = epoch_block_query.to_pandas().reset_index()

    df_exp_search = populate_ndf_column(df_exp_search)

    df_exp_search["datafile_name"] = df_exp_search["data_dir"].apply(
        lambda x: os.path.split(x)[-1]
    )

    # order columns
    ls_order = [
        "exp_name",
        "datafile_name",
        "NDF",
        "chunk_name",
        "protocol_name",
        "is_mea",
        "data_dir",
        "group_label",
        "experiment_id",
        "protocol_id",
        "group_id",
        "block_id",
        "chunk_id",
    ]
    df_exp_search = df_exp_search[ls_order]

    n_experiments = df_exp_search["exp_name"].nunique()
    n_blocks = len(df_exp_search)

    if verbose:
        print(f"\nFound {n_experiments} experiments, {n_blocks} epoch blocks.\n")

    return df_exp_search


def get_noise_chunks_sorted_by_distance(
    df_exp_summary: pd.DataFrame,
    datafile_name: str,
    noise_protocol_name: str = "manookinlab.protocols.SpatialNoise",
    verbose: bool = False,
):
    """
    Function for pulling noise chunks sorted by their distance to the protocol of interest, as identified by a datafile.

    Parameters:
    df_exp_summary (pandas DataFrame): an experiment summary dataframe as generated by get_exp_summary function

    datafile_name (str): name of the protocol datafile of interest (e.g. data008)

    noise_protocol_name (str): name of the noise protocol used in that experiment (default is manookinlab.protocols.SpatialNoise)

    verbose (bool): Verbose output prints status to console. Default is False

    Returns:
    noise_chunk_names List[str]: chunk names (i.e. 'chunk3') in order of nearest to furtherst

    noise_chunk_distances List[int]: distance in minutes for each listed noise chunk in order
    from closest to furthest.
    """

    prot_row = df_exp_summary.query("datafile_name == @datafile_name")
    prot_start_time = prot_row["start_time"].values[0]
    prot_end_time = prot_row["end_time"].values[0]

    noise_chunk_names = df_exp_summary.query("protocol_name == @noise_protocol_name")[
        "chunk_name"
    ].unique()
    noise_chunk_distances = []

    for chunk_name in noise_chunk_names:
        # if chunk_name == prot_chunk_name:
        # noise_chunk_distances.append((chunk_name, 0.0))
        # continue
        noise_rows = df_exp_summary.query(
            "chunk_name == @chunk_name and protocol_name == @noise_protocol_name"
        )
        noise_start_time = noise_rows["start_time"].values[0]
        noise_end_time = noise_rows["end_time"].values[-1]
        if noise_start_time < prot_start_time:
            distance = prot_start_time - noise_end_time
        else:
            distance = noise_start_time - prot_end_time
        # Convert to minutes
        distance = distance / np.timedelta64(1, "m")
        noise_chunk_distances.append(distance)
    noise_chunk_names = noise_chunk_names[np.argsort(noise_chunk_distances)]
    noise_chunk_distances = np.sort(noise_chunk_distances)

    if verbose:
        print(
            f'Found {len(noise_chunk_names)} noise chunks for protocol "{noise_protocol_name}"'
        )
        print("Noise chunks sorted by distance:")
        for chunk_name, distance in zip(noise_chunk_names, noise_chunk_distances):
            print(f"  {chunk_name}: {distance:.2f} minutes")

    return noise_chunk_names, noise_chunk_distances


def find_datafile_for_protocol(
    df_exp_search: pd.DataFrame,
    exp_name: str,
    protocol_name: Optional[str] = None,
    verbose: bool = True,
):
    """
    NEW 2026-07-29 (Claude, per yas): pick which datafile_name to use for a given
    experiment out of a dataset-search dataframe, so notebooks don't need the user
    to type in a specific datafile_name by hand once they've already searched for
    the protocol they want.

    If there's exactly one matching row for exp_name (and protocol_name, if given),
    that datafile_name is returned. If there's more than one (the protocol was run
    more than once that day -- e.g. re-run with different parameters), the earliest
    one by block_id is used, and every candidate found is printed so it's obvious
    whether a different one should be picked instead.

    Parameters:
    df_exp_search (pandas DataFrame): a dataset-search dataframe, e.g. the output of
    get_datasets_from_protocol_names(). Must have 'exp_name' and 'datafile_name'
    columns; 'protocol_name' and 'block_id' are used if present (protocol_name to
    filter, block_id to order candidates chronologically).

    exp_name (str): which experiment to pick a datafile for.

    protocol_name (Optional[str]): if given, further filters df_exp_search to rows
    with this exact protocol_name before picking. Default None -- no extra
    filtering, so if df_exp_search might contain more than one protocol's rows
    (e.g. a broad substring search), pass this to avoid picking a datafile from the
    wrong protocol.

    verbose (bool): print what was found/chosen. Default True.

    Returns:
    datafile_name (str or None): the chosen datafile name (e.g. 'data003'), or None
    if no matching row was found for exp_name (and protocol_name, if given).
    """
    matches = df_exp_search.query("exp_name == @exp_name")
    if protocol_name is not None and "protocol_name" in matches.columns:
        matches = matches.query("protocol_name == @protocol_name")

    if "datafile_name" in matches.columns:
        matches = matches.drop_duplicates(subset="datafile_name")

    if len(matches) == 0:
        if verbose:
            proto_msg = f' for protocol "{protocol_name}"' if protocol_name else ""
            print(
                f"No datafile found for {exp_name}{proto_msg} in the given search "
                "results."
            )
        return None

    if "block_id" in matches.columns:
        matches = matches.sort_values("block_id")

    chosen = matches.iloc[0]["datafile_name"]

    if verbose:
        if len(matches) > 1:
            print(
                f"{exp_name}: {len(matches)} matching datafiles found: "
                f"{list(matches['datafile_name'])}. Using the earliest, {chosen}. "
                "Pass a different datafile_name directly if you want a different one."
            )
        else:
            print(f"{exp_name}: using datafile {chosen}.")

    return chosen


def find_classified_noise_chunk(
    exp_name: str,
    preferred_ndfs: List[float] = (0, 1),
    ss_version: str = "kilosort2.5",
    verbose: bool = True,
):
    """
    NEW 2026-07-28 (Claude, per yas): auto-pick a noise (cell-typing) chunk for an
    experiment, following this lab's specific convention rather than
    create_mea_pipeline's default "nearest chunk in time" heuristic. That default
    can land on a chunk that's a dead/partial recording or simply lacks a
    classification file, which then crashes downstream (either with "no typing
    file" or, if the chunk's .globals file is incomplete, "Globals file does not
    have RTMP tag").

    Convention (per yas, 2026-07-29): prefer the white-noise chunk at NDF 0 that
    has a classification file. If NDF 0 was never classified (e.g. the recording
    died before reaching NDF 0, so the lab classified NDF 1 instead), fall back to
    NDF 1. If more than one chunk at the chosen NDF has a classification file
    (e.g. white noise was re-run with different parameters and both got
    classified), the earliest one (by start time) is used, and this prints all the
    candidates found plus which one was picked, so you can tell at a glance if you
    want a different one. Nothing beyond NDF 1 is tried automatically -- if
    neither NDF 0 nor NDF 1 has a classified chunk, this returns None and prints
    why, rather than guessing further.

    This function only does a filesystem check for classification files (same
    "any filename containing 'classification', case-insensitive" rule used by
    plot_mosaics_for_datasets) -- it does NOT instantiate AnalysisChunk or load
    anything from the .globals file, so it works even for chunks whose .globals
    file is missing the RTMP tag (which would otherwise make AnalysisChunk crash
    before you ever found out whether that chunk was classified). Whatever chunk
    name this returns is meant to be passed straight to
    create_mea_pipeline(..., analysis_chunk_name=<result>) to skip its own
    nearest-chunk auto-detection.

    Parameters:
    exp_name (str): experiment name, e.g. '20250910A'.

    preferred_ndfs (List[float]): NDF values to try, in priority order. Default
    (0, 1) -- NDF 0 first, NDF 1 as the only fallback. Pass your own list/order if
    a different lab convention applies (e.g. (0,) to never fall back to NDF 1).

    ss_version (str): spike-sorting version subfolder to look for classification
    files in, default 'kilosort2.5'. Only used to build the on-disk path -- if
    that exact folder doesn't exist, common alternates (kilosort25, kilosort40,
    kilosort4, combined) are tried too, same as AnalysisChunk does.

    verbose (bool): print what was found/chosen and why. Default True -- this is
    meant to be read, since it's making a choice for you.

    Returns:
    identifier (str or None): the chosen chunk_name (older experiments that still
    have real SortingChunk rows, e.g. 'chunk13') or datafile_name (newer
    experiments where SortingChunk isn't populated, e.g. 'data001' -- see "no
    more chunks" note below) -- either way, meant to be passed straight to
    create_mea_pipeline(..., analysis_chunk_name=<result>). Returns None if no
    classified chunk was found at any of preferred_ndfs.
    """
    # CHANGED 2026-07-29 (Claude, per yas -- "we don't have chunks anymore, I
    # changed the datajoint structure to align with our new one"): this used to
    # filter to chunk_name.str.contains("chunk"), copied from the existing (never
    # updated for the new structure) get_nearest_noise() in stim.py. That's wrong
    # for yas's current schema: get_exp_summary() (see its own comments) now
    # returns chunk_name="" for any experiment where SortingChunk rows aren't
    # populated, which is normal for the newer data-directory-based layout where
    # each datafile (data000, data001, ...) is its own analysis unit rather than
    # being grouped into named "chunks". A literal "chunk" substring match would
    # silently exclude every white-noise row for those experiments. Fixed: no
    # longer filters on chunk_name content at all -- just protocol_name. Uses
    # chunk_name when it's actually populated (a non-empty string, for older
    # experiments that do have real SortingChunk rows), otherwise falls back to
    # datafile_name (for newer experiments), since that's what AnalysisChunk needs
    # to actually find the right directory on disk either way.
    from retinanalysis.utils.vision_utils import _resolve_vision_data_path

    df_exp_summary = get_exp_summary(exp_name)
    if df_exp_summary is None or len(df_exp_summary) == 0:
        if verbose:
            print(f"No experiment summary found for {exp_name}, cannot pick a noise chunk.")
        return None

    noise_protocol_name = get_noise_name_by_exp(exp_name)
    noise_rows = df_exp_summary.query("protocol_name == @noise_protocol_name").copy()

    if len(noise_rows) == 0:
        if verbose:
            print(
                f'No "{noise_protocol_name}" runs found at all for {exp_name} -- '
                "cannot pick a noise chunk."
            )
        return None

    noise_rows["_resolved_id"] = noise_rows.apply(
        lambda row: row["chunk_name"]
        if isinstance(row["chunk_name"], str) and row["chunk_name"].strip()
        else row["datafile_name"],
        axis=1,
    )
    noise_chunks = noise_rows.drop_duplicates(subset="_resolved_id").sort_values(
        "minutes_since_start"
    )

    for i_pref, ndf_target in enumerate(preferred_ndfs):
        ndf_chunks = noise_chunks[noise_chunks["NDF"] == ndf_target]

        if len(ndf_chunks) == 0:
            if verbose:
                print(f"{exp_name}: no white-noise chunk found at NDF {ndf_target}.")
            continue

        classified = []
        for _, row in ndf_chunks.iterrows():
            chunk_name = row["_resolved_id"]
            data_path = _resolve_vision_data_path(exp_name, chunk_name, ss_version)
            try:
                classification_files = [
                    f for f in os.listdir(data_path) if "classification" in f.lower()
                ]
            except Exception as e:
                if verbose:
                    print(f"  Could not list files for {chunk_name} ({data_path}): {e}")
                classification_files = []

            if classification_files:
                classified.append((chunk_name, row["block_id"], classification_files))

        if not classified:
            if verbose:
                print(
                    f"{exp_name}: NDF {ndf_target} has {len(ndf_chunks)} white-noise "
                    f"chunk(s) ({list(ndf_chunks['_resolved_id'])}), but none have a "
                    "classification file."
                )
            continue

        if i_pref > 0 and verbose:
            print(
                f"{exp_name}: NDF {preferred_ndfs[0]} had no classified chunk, "
                f"falling back to NDF {ndf_target}."
            )

        chosen_chunk_name, chosen_block_id, chosen_files = classified[0]

        if verbose:
            if len(classified) > 1:
                print(
                    f"{exp_name}: {len(classified)} classified chunks found at NDF "
                    f"{ndf_target}: {[c[0] for c in classified]}. Using the earliest, "
                    f"{chosen_chunk_name} (classification file(s): {chosen_files}). "
                    "Pass a different chunk name as analysis_chunk_name= to "
                    "create_mea_pipeline if you want a different one."
                )
            else:
                print(
                    f"{exp_name}: using {chosen_chunk_name} (NDF {ndf_target}, "
                    f"classification file(s): {chosen_files})."
                )

            try:
                ep_q = schema.Epoch() & f"parent_id={chosen_block_id}"
                ep_id = ep_q.to_arrays("id")[0]
                params = (schema.Epoch() & f"id={ep_id}").fetch1("parameters")
                print(f"  Stimulus parameters for {chosen_chunk_name}:")
                for k in sorted(params.keys()):
                    print(f"    {k}: {params[k]}")
            except Exception as e:
                print(f"  Could not fetch stimulus parameters for {chosen_chunk_name}: {e}")

        return chosen_chunk_name

    if verbose:
        print(
            f"{exp_name}: no classified white-noise chunk found at any of "
            f"NDF {list(preferred_ndfs)}. Returning None -- create_mea_pipeline will "
            "fall back to its own nearest-chunk logic unless you pass "
            "analysis_chunk_name explicitly."
        )
    return None


def get_n_cells_of_interest(
    str_file: str, ls_cell_types: list = ["OffP", "OffM", "OnP", "OnM"]
):
    # str_file is cell typing file path
    # Returns the number of cells of interest in the typing file
    if not os.path.exists(str_file):
        print(f"Cell typing file {str_file} does not exist!")
        return 0
    try:
        arr_types = np.genfromtxt(str_file, dtype=str, delimiter="  ")
        if len(arr_types.shape) != 2:
            try_shape = arr_types.shape
            # Try 1 space delimiter
            arr_types = np.genfromtxt(str_file, dtype=str, delimiter=" ")
            if len(arr_types.shape) != 2:
                print(f"Could not parse {str_file}")
                print(f"Error: 2 space delimiter resulted in {try_shape} shape")
                print(f"Error: 1 space delimiter resulted in {arr_types.shape} shape")
                return 0
    except:
        print(
            f"Error reading cell typing file {str_file}. Please check the file format."
        )
        return 0
    n_cells = 0
    # 2nd column of arr_types contains cell types, where we want to match substring after .lower()
    for str_match in ls_cell_types:
        ls_match = []
        for i in range(len(arr_types)):
            str_cell_type = arr_types[i, 1].lower()
            if str_match.lower() in str_cell_type:
                ls_match.append(arr_types[i, 0])
        n_cells += len(ls_match)
    return n_cells


def get_noise_name_by_exp(exp_name: str) -> str:
    """
    Function that pulls the appropriate noise protocol name based on
    when the experiment was run (fast nosie for before 20230926, and
    spatial noise for after)

    Parameters:
    exp_name (str): name of experiment (i.e. 20251008C)

    Returns:
    noise_protocol_name (str): name of noise protocol used for typing
    and sorting in that experiment.
    """

    if int(exp_name[:8]) < 20230926:
        noise_protocol_name = "manookinlab.protocols.FastNoise"
    else:
        noise_protocol_name = "manookinlab.protocols.SpatialNoise"

    return noise_protocol_name


def get_stage_frame_rate_by_exp(exp_name: str, verbose: bool = True) -> float:
    exp_query = schema.Experiment() & f'exp_name="{exp_name}"'
    exp_id = exp_query.fetch1("id")
    epochblock_query = schema.EpochBlock() & f"experiment_id={exp_id}"
    # Get epochs for all these epoch blocks based on id (parent_id)
    epoch_query = schema.Epoch() & [f"parent_id={eb_id}" for eb_id in epochblock_query.to_arrays("id")]
    epoch_query = epoch_query.proj(stage_frame_rate="parameters->>'$.frameRate'")
    stage_frame_rates = epoch_query.to_arrays("stage_frame_rate")
    stage_frame_rates = stage_frame_rates.astype(float)
    # Remove NaN values if any
    stage_frame_rates = stage_frame_rates[~np.isnan(stage_frame_rates)]

    if len(np.unique(stage_frame_rates)) != 1:
        keep_rate = min(stage_frame_rates)
        if verbose:
            print(
                f"Warning: Multiple stage frame rates found for experiment {exp_name}: {np.unique(stage_frame_rates)}"
            )
            print(f"This could be due to PatternMode usage.")
            print(f"d_display will keep the min: {keep_rate}")
    else:
        keep_rate = stage_frame_rates[0]
        if verbose:
            print(f"Found stage frame rate {keep_rate} for experiment {exp_name}")

    return keep_rate


def get_display_params_by_exp(exp_name: str, verbose: bool = True):
    # Rig H
    if "H" in exp_name:
        if verbose:
            print(f"For Rig H {exp_name}:")
        if int(exp_name[:8]) > 20230926:
            disp_type = "LCR"
            mu_per_pixel = 3.24
            n_ht = 1140
            n_wt = 1824
            mean_frame_rate = 59.941548817817917
        else:
            raise NotImplementedError("OLED display params not defined for Rig H yet.")

    # Rig C
    elif "C" in exp_name:
        if verbose:
            print(f"For Rig C {exp_name}:")
        if int(exp_name[:8]) < 20230926:
            disp_type = "OLED"
            mu_per_pixel = 3.8
            n_ht = 600
            n_wt = 800
            mean_frame_rate = 60.31807657
        else:
            disp_type = "LCR"
            # As saved in sta_analysis.py. Rig Config indicates 3.37 so not sure what's best...
            # I figure sta_analysis.py value is better as that's used to generate STAs
            # and will be useful to convert regen stim from pixel to stixel space.
            if int(exp_name[:8]) < 20260312:
                mu_per_pixel = 3.34
            else:
                mu_per_pixel = 3.07
            n_ht = 1140
            n_wt = 1824
            mean_frame_rate = 59.941548817817917
    # Rig E (Fred confocal)
    elif "E" in exp_name:
        if verbose:
            print(
                f"For Rig E {exp_name}, assuming ConfocalWithLightCrafterAbove rig config:"
            )
        disp_type = "LCR"
        mu_per_pixel = 1.3
        n_ht = 1140
        n_wt = 1824
        mean_frame_rate = 59.9422

    # Rig A (Greg, added by Yasmine 07/08/2026)
    elif "A" in exp_name:
        if verbose:
            print(
                f"For Rig E {exp_name}, assuming ConfocalWithLightCrafterAbove rig config:"
            )
        disp_type = "LCR"
        mu_per_pixel = 7.6
        n_ht = 912
        n_wt = 1140
        mean_frame_rate = 59.941548817817917
    else:
        raise ValueError(
            f"Unexpected Rig identified in MEA experiment name {exp_name} !"
        )

    stage_frame_rate = get_stage_frame_rate_by_exp(exp_name, verbose)

    d_display = {
        "disp_type": disp_type,
        "mu_per_pixel": mu_per_pixel,
        "n_ht": n_ht,
        "n_wt": n_wt,
        "mean_frame_rate": mean_frame_rate,
        "stage_frame_rate": stage_frame_rate,
    }
    if verbose:
        print(d_display)
    return d_display


def get_typing_files_for_datasets(
    df: pd.DataFrame,
    ls_cell_types: list = ["OffP", "OffM", "OnP", "OnM"],
    verbose: bool = False,
):
    # Return df_typed with columns:
    # exp_name, datafile_names, chunk_name, protocol_name, ss_version, typing_file_name, typing_file_path
    # Each row corresponds to a typing file for the nearest noise chunk.
    # And df_not_typed with columns:
    # exp_name, datafile_names, nearest_noise_chunk, nearest_noise_distance
    # Each row corresponds to a dataset without any typing files.
    d_not_typed = {
        "exp_name": [],
        "datafile_name": [],
        "chunk": [],
        "nearest_noise_chunk": [],
        "nearest_noise_distance": [],
    }
    d_typed = {
        "exp_name": [],
        "datafile_name": [],
        "chunk": [],
        "nearest_noise_chunk": [],
        "nearest_noise_distance": [],
        "typed_noise_chunk": [],
        "nearest_noise_distance": [],
        "typed_noise_distance": [],
        "is_nearest": [],
        "ss_version": [],
        "noise_datafile_names": [],
        "typing_file_name": [],
        "typing_file_path": [],
        "typing_file_id": [],
        "n_cells_of_interest": [],
    }
    for exp_name in tqdm(
        df["exp_name"].unique(), desc="Finding typing files for unique experiments"
    ):
        df_q: pd.DataFrame = df.query("exp_name==@exp_name")

        exp_summary = get_exp_summary(exp_name)
        assert exp_summary is not None, (
            f"Failed to generate experiment summary for {exp_name}"
        )
        df_exp: pd.DataFrame = exp_summary

        noise_protocol_name: str = get_noise_name_by_exp(exp_name)

        for datafile_name in df_q["datafile_name"].values:
            chunk = df_exp.query("datafile_name == @datafile_name")[
                "chunk_name"
            ].values[0]
            noise_chunk_names, noise_chunk_distances = (
                get_noise_chunks_sorted_by_distance(
                    df_exp, datafile_name, noise_protocol_name, verbose
                )
            )

            # Find nearest noise chunk with typing.
            b_found = False
            nearest_noise_chunk = noise_chunk_names[0]
            for i_c, noise_chunk in enumerate(noise_chunk_names):
                df_chunk = df_exp.query(
                    "chunk_name == @noise_chunk and protocol_name == @noise_protocol_name"
                )
                noise_chunk_id = df_chunk["chunk_id"].values[0]
                noise_datafile_names = list(df_chunk["datafile_name"].values)
                df_ct = (
                    schema.CellTypeFile() & {"chunk_id": noise_chunk_id}
                ).to_pandas()

                if not b_found and len(df_ct) > 0:
                    for i_ct in df_ct.index:
                        ss_version = df_ct.at[i_ct, "algorithm"]
                        typing_file_name = df_ct.at[i_ct, "file_name"]
                        typing_file_path = os.path.join(
                            QUERY_DIR,
                            exp_name,
                            noise_chunk,
                            ss_version,
                            typing_file_name,
                        )
                        n_cells_of_interest = get_n_cells_of_interest(
                            typing_file_path, ls_cell_types
                        )
                        d_typed["exp_name"].append(exp_name)
                        d_typed["datafile_name"].append(datafile_name)
                        d_typed["chunk"].append(chunk)
                        d_typed["nearest_noise_chunk"].append(nearest_noise_chunk)
                        d_typed["nearest_noise_distance"].append(
                            noise_chunk_distances[0]
                        )
                        d_typed["typed_noise_chunk"].append(noise_chunk)
                        d_typed["typed_noise_distance"].append(
                            noise_chunk_distances[i_c]
                        )
                        d_typed["noise_datafile_names"].append(noise_datafile_names)
                        d_typed["ss_version"].append(ss_version)
                        d_typed["typing_file_name"].append(typing_file_name)
                        d_typed["typing_file_path"].append(typing_file_path)
                        d_typed["typing_file_id"].append(i_ct)
                        d_typed["n_cells_of_interest"].append(n_cells_of_interest)
                        if noise_chunk == nearest_noise_chunk:
                            d_typed["is_nearest"].append(True)
                        else:
                            d_typed["is_nearest"].append(False)
                    b_found = True

            # If no cell typing files found, append to d_not_typed
            if not b_found:
                d_not_typed["exp_name"].append(exp_name)
                d_not_typed["datafile_name"].append(datafile_name)
                d_not_typed["chunk"].append(
                    df_exp.query("datafile_name == @datafile_name")[
                        "chunk_name"
                    ].values[0]
                )
                d_not_typed["nearest_noise_chunk"].append(nearest_noise_chunk)
                d_not_typed["nearest_noise_distance"].append(noise_chunk_distances[0])

    df_typed = pd.DataFrame(d_typed)
    df_not_typed = pd.DataFrame(d_not_typed)
    return df_typed, df_not_typed


def plot_mosaics_for_all_datasets(
    df: pd.DataFrame,
    ls_cell_types: list = ["OffP", "OffM", "OnP", "OnM"],
    n_top: Optional[int] = None,
):

    from retinanalysis.classes.analysis_chunk import AnalysisChunk

    # df should be output of get_datasets_from_protocol_names
    df_typed, df_not_typed = get_typing_files_for_datasets(df, ls_cell_types)
    print(f"Found {df_not_typed.shape[0]} datasets without any typing files:")
    display(df_not_typed)
    print(f"Found {df_typed.shape[0]} datasets with typing files.")

    # Keep only those with n_cells_of_interest > 0
    df_u = df_typed.query("n_cells_of_interest > 0")
    # Sort by n_cells_of_interest
    df_u = df_u.sort_values("n_cells_of_interest", ascending=False)
    df_u = df_typed[["exp_name", "typed_noise_chunk"]].drop_duplicates()

    if n_top is None:
        n_top = 20
    print(
        f"Found {df_u.shape[0]} unique datasets with typing files and > 0  cells of interest."
    )
    for u_idx in df_u.index[:n_top]:
        exp_name = df_u.at[u_idx, "exp_name"]

        chunk_name = df_u.at[u_idx, "typed_noise_chunk"]
        df_q = df_typed.query(
            f'exp_name == "{exp_name}" and typed_noise_chunk == "{chunk_name}"'
        )
        df_q = df_q.reset_index(drop=True)
        datafile_names = df_q["datafile_name"].unique()

        # Find row with max n_cells_of_interest
        row = df_q.loc[df_q["n_cells_of_interest"].idxmax()]
        ss_version = row["ss_version"]
        typing_file = row["typing_file_name"]
        try:
            ac1 = AnalysisChunk(
                exp_name,
                chunk_name,
                ss_version,
                b_load_spatial_maps=False,
                include_ei=False,
                include_neurons=False,
                verbose=False,
            )

            axs = ac1.plot_rfs(
                typing_file=typing_file,
                cell_types=ls_cell_types,
                units="microns",
                std_scaling=1.0,
                b_zoom=True,
                n_pad=6,
            )
            f = axs[0].get_figure()
            nearest_chunk = row["nearest_noise_chunk"]
            str_title = f"{exp_name} {chunk_name} {ss_version} {typing_file}\nfor {datafile_names}"
            if nearest_chunk != chunk_name:
                str_title += f"\n(nearest chunk: {nearest_chunk})"
            f.suptitle(str_title, y=1.05)
            for ax in axs:
                ax.set_aspect("equal", adjustable="box")
        except Exception as e:
            print(
                f"Error processing {exp_name}, {datafile_names}, {chunk_name}, {ss_version}, {typing_file}: {e}"
            )
            continue
    return df_typed, df_not_typed


def find_varying_epoch_parameters(df: pd.DataFrame):
    """
    Helper function for finding parameters that change from epoch to epoch, as opposed
    to epoch block parameters which should remain the same. This function creates an
    automated list of varying params to add to the df_epochs dataframe built
    into the stim_block object.

    NOTE: This is only a helper function used by the get_epoch_data_from_exp function,
    should not be called on its own.
    """

    # df should have epoch data for a SINGLE EpochBlock.
    # Thus assuming that all epoch parameter dictionaries have the same keys.
    # The epoch_parameters column has dictionaries of {parameter_name: value}
    # We want to find which parameters vary across epochs in the dataframe
    varying_params = set()
    idx = df.index[0]
    param_names = df.at[idx, "epoch_parameters"].keys()
    for key in param_names:
        # Get all values across all epochs
        values = df["epoch_parameters"].apply(lambda x: x.get(key)).values
        # Check if all None
        if all(value is None for value in values):
            continue
        if len(np.unique(values)) > 1:
            varying_params.add(key)
    return list(varying_params)


def add_parameters_col(df, ls_params, src_col: str = "epoch_parameters"):
    # Add a column to the dataframe that contains the values of the specified parameters
    # src_col should have dictionaries of {parameter_name: value}
    for param in ls_params:
        df[param] = df[src_col].apply(lambda x: x.get(param))
    return df


def get_epoch_data_from_exp(
    exp_name: str,
    block_id: int,
    b_LED: Optional[bool] = False,
    ls_params: Optional[List] = None,
    stim_time_name: str = "stimTime",
) -> pd.DataFrame:
    # Filter Experiment by exp_name, EpochBlock by block_id, then join down to Epoch
    exp_query = schema.Experiment() & f'exp_name="{exp_name}"'
    is_mea = exp_query.fetch1("is_mea") == 1
    epochgroup_query = schema.EpochGroup() * exp_query.proj("exp_name", experiment_id="id")
    epochgroup_query = epochgroup_query.proj("exp_name", "experiment_id", group_label="label", group_id="id")

    ls_eb_cols = ["protocol_id"]
    if is_mea:
        ls_eb_cols += ["data_dir"]
    epochblock_query = schema.EpochBlock.proj(
        *ls_eb_cols,
        group_id="parent_id",
        block_properties="properties",
        block_id="id",  # type: ignore
    )

    epochblock_query = epochgroup_query * epochblock_query
    epochblock_query = epochblock_query & f"block_id={block_id}"

    if is_mea:
        # Check num epoch ends matches num epoch starts
        eb_df = epochblock_query.to_pandas().reset_index()
        d_data = eb_df.loc[0].to_dict()
        epoch_starts = d_data["block_properties"]["epochStarts"]
        epoch_ends = d_data["block_properties"]["epochEnds"]

    protocol_query = epochblock_query * schema.Protocol.proj(protocol_name="name")  # type: ignore

    epoch_query = protocol_query * schema.Epoch.proj(
        epoch_parameters="parameters",
        block_id="parent_id",
        epoch_id="id",
        frame_times_ms="properties->>'$.frameTimesMs'",
    )  # type: ignore

    df = epoch_query.to_pandas()
    df = df.reset_index()

    if is_mea:
        df["datafile_name"] = df["data_dir"].apply(lambda x: os.path.split(x)[-1])

    varying_params = find_varying_epoch_parameters(df)
    # Add ls_params to varying_params if provided
    if ls_params is not None:
        varying_params = list(set(varying_params).union(set(ls_params)))
    df = add_parameters_col(df, varying_params, "epoch_parameters")

    # Add preTime, stimTime, tailTime
    ls_time_cols = ["preTime", stim_time_name, "tailTime"]
    df = add_parameters_col(df, ls_time_cols, "epoch_parameters")
    if is_mea:
        ls_order = (
            varying_params
            + [
                "exp_name",
                "datafile_name",
                "group_label",
                "protocol_name",
                "frame_times_ms",
                "epoch_parameters",
                "data_dir",
            ]
            + ls_time_cols
            + ["experiment_id", "group_id", "block_id", "protocol_id", "epoch_id"]
        )
    else:
        ls_order = (
            varying_params
            + [
                "exp_name",
                "group_label",
                "protocol_name",
                "frame_times_ms",
                "epoch_parameters",
            ]
            + ls_time_cols
            + ["experiment_id", "group_id", "block_id", "protocol_id", "epoch_id"]
        )
    df = df[ls_order]

    if b_LED:
        # Delete frame_times_ms column
        df = df.drop(columns=["frame_times_ms"])
    else:
        # Make frame_times_ms list using json.loads
        df["frame_times_ms"] = df["frame_times_ms"].apply(lambda x: json.loads(x))

    # Add column for 'epoch_index'
    df.index = df.index.rename("epoch_index")
    df = df.reset_index(drop=False)

    if is_mea:
        if len(epoch_ends) == len(epoch_starts) - 1:
            print(
                f"Warning: For {exp_name} block {block_id}, found {len(epoch_ends)} epoch ends but {len(epoch_starts)} epoch starts."
            )
            print(f"Removing last epoch from dataframe")
            df = df.iloc[:-1, :]

    return df


def get_epochblock_query(exp_name: str, block_id: int):
    exp_query = schema.Experiment() & f'exp_name="{exp_name}"'
    epochgroup_query = schema.EpochGroup() * exp_query.proj("exp_name", "is_mea", experiment_id="id")
    epochgroup_query = epochgroup_query.proj("exp_name", "is_mea", group_label="label", group_id="id")
    epochblock_query = schema.EpochBlock.proj(
        "protocol_id",
        "data_dir",
        block_properties="properties",  # type: ignore
        group_id="parent_id",
        block_id="id",
    )
    epochblock_query = epochgroup_query * epochblock_query
    epochblock_query = epochblock_query & f"block_id={block_id}"
    return epochblock_query


def get_epochblock_timing(exp_name: str, block_id: int, b_LED: bool = False) -> dict:
    epochblock_query = get_epochblock_query(exp_name, block_id)
    df = epochblock_query.to_pandas().reset_index()
    if len(df) > 1:
        raise ValueError(
            f"Expected only one EpochBlock for {exp_name} {block_id}, but found {len(df)}"
        )
    if len(df) == 0:
        raise ValueError(f"No EpochBlock found for {exp_name} {block_id}")
    d_data = df.loc[0].to_dict()
    is_mea = df.loc[0, "is_mea"]

    d_timing = {"exp_name": exp_name, "block_id": block_id}

    # For MEA data, 'block_properties' has epoch_starts, epoch_ends, n_samples, and if LED frame_times_ms
    # For SC data, this has just frame_times_ms
    if not b_LED:
        d_timing["frameTimesMs"] = d_data["block_properties"]["frameTimesMs"]

    if is_mea:
        epoch_starts = d_data["block_properties"]["epochStarts"]
        epoch_ends = d_data["block_properties"]["epochEnds"]

        # i think if symphony crashed during recording, there might be more 1 more start than end
        # this ignores the partial epoch
        if len(epoch_ends) == len(epoch_starts) - 1:
            print(
                f"Warning: For {exp_name} block {block_id}, found {len(epoch_ends)} epoch ends but {len(epoch_starts)} epoch starts."
            )

            # Remove last epoch start
            epoch_starts = epoch_starts[: len(epoch_ends)]
            print(f"Keeping only {len(epoch_starts)} epochs.")

            if not b_LED:
                # Remove last epoch of frame times as well
                d_timing["frameTimesMs"].pop()

        elif len(epoch_ends) != len(epoch_starts):
            if len(epoch_ends) > len(epoch_starts):
                n_extra_ends = len(epoch_ends) - len(epoch_starts)
                print(
                    f"Epoch Starts: {[(i, epoch_starts[i]) for i in range(len(epoch_starts))]}"
                )
                print(
                    f"Epoch Ends: {[(i, epoch_ends[i]) for i in range(len(epoch_ends))]}\n"
                )
                for _ in range(n_extra_ends):
                    idx_to_remove = input(
                        "More ends than starts, select index (from 0) to remove:"
                    )
                    print(f"Removing epoch end #{int(idx_to_remove)}\n")
                    epoch_ends.pop(int(idx_to_remove))
                    print(
                        f"Epoch Starts: {[(i, epoch_starts[i]) for i in range(len(epoch_starts))]}"
                    )
                    print(
                        f"Epoch Ends: {[(i, epoch_ends[i]) for i in range(len(epoch_ends))]}\n"
                    )
            elif len(epoch_starts) > len(epoch_ends):
                n_extra_starts = len(epoch_starts) - len(epoch_ends)
                print(
                    f"Epoch Starts: {[(i, epoch_starts[i]) for i in range(len(epoch_starts))]}"
                )
                print(
                    f"Epoch Ends: {[(i, epoch_ends[i]) for i in range(len(epoch_ends))]}\n"
                )
                for _ in range(n_extra_starts):
                    idx_to_remove = input(
                        "More starts than ends, select index (from 0) to remove:"
                    )
                    print(f"Removing epoch start #{int(idx_to_remove)}\n")
                    epoch_starts.pop(int(idx_to_remove))
                    print(
                        f"Epoch Starts: {[(i, epoch_starts[i]) for i in range(len(epoch_starts))]}"
                    )
                    print(
                        f"Epoch Ends: {[(i, epoch_ends[i]) for i in range(len(epoch_ends))]}\n"
                    )
            else:
                raise ValueError(
                    f"Mismatch in number of epoch starts and ends: {len(epoch_starts)} starts and but {len(epoch_ends)} ends."
                )

        d_timing["epochStarts"] = epoch_starts
        d_timing["epochEnds"] = epoch_ends
        d_timing["n_samples"] = d_data["block_properties"]["n_samples"]

    # Get stim timing and frame rate
    epoch_query = schema.Epoch() & f"parent_id={block_id}"
    n_epochs = len(epoch_query)

    # If mea, check for inequality with number of epochStarts and epochs of metadata
    if is_mea:
        n_epoch_times = len(d_timing["epochStarts"])
        # Can have 1 more metadata entry in case of failed TTL signal... in that case throwing away metadata and using only those epochs
        # where we have reliable starts and stops.
        if n_epochs > n_epoch_times:
            print(
                f"Warning: For {exp_name} block {block_id}, found {n_epochs} epochs in metadata but only {n_epoch_times} epoch starts."
            )
            print(f"Assuming n_epochs = {n_epoch_times}")
            n_epochs = n_epoch_times
        # Can have 1 less metadata entry in case of symphony crash... in that case, throwing away the epoch starts and stops that have no
        # associated metadata
        elif n_epochs < n_epoch_times:
            print(
                f"Warning: for {exp_name} block {block_id}, found {n_epoch_times} epoch starts but only {n_epochs} epochs in metadata."
            )
            print(f"Assuming there are {n_epochs} completed epochs.")
            d_timing["epochStarts"] = d_timing["epochStarts"][:n_epochs]
            d_timing["epochEnds"] = d_timing["epochEnds"][:n_epochs]

    d_timing["n_epochs"] = n_epochs

    epoch_query = epoch_query.proj(
        pre_time="parameters->>'$.preTime'",
        stim_time="parameters->>'$.stimTime'",
        tail_time="parameters->>'$.tailTime'",
        stage_frame_rate="parameters->>'$.frameRate'",
    )

    df_transitions = epoch_query.to_pandas().drop_duplicates().reset_index()

    if len(df_transitions) != 1:
        display(df_transitions)
        raise ValueError(
            f"Expected a unique set of timing parameters for {exp_name} {block_id}, but found {len(df_transitions)}"
        )

    # Check if preTime, stimTime and tailTime exist, which they sometimes don't for LED stimuli.
    if df_transitions.at[0, "pre_time"] is None:
        print(
            f"Warning: preTime not found for {exp_name} block {block_id}. Possible for LED stimuli, setting to 0."
        )
        df_transitions.loc[0, "pre_time"] = 0

    if df_transitions.at[0, "stim_time"] is None:
        print(
            f"Warning: stimTime not found for {exp_name} block {block_id}. Possible for LED stimuli, setting to 0."
        )
        df_transitions.loc[0, "stim_time"] = 0

    if df_transitions.at[0, "tail_time"] is None:
        print(
            f"Warning: tailTime not found for {exp_name} block {block_id}. Possible for LED stimuli, setting to 0."
        )
        df_transitions.loc[0, "tail_time"] = 0

    pre_time_ms = float(df_transitions.at[0, "pre_time"])
    stim_time_ms = float(df_transitions.at[0, "stim_time"])
    tail_time_ms = float(df_transitions.at[0, "tail_time"])

    d_timing["pre_time_ms"] = pre_time_ms
    d_timing["stim_time_ms"] = stim_time_ms
    d_timing["tail_time_ms"] = tail_time_ms

    if not b_LED:
        stage_frame_rate = df_transitions.loc[0, "stage_frame_rate"]
        if stage_frame_rate is None:
            print(
                f"Warning: for {exp_name} block {block_id}, error in finding stage frame rate."
            )
            print(f"If this is for an LED stimulus, be sure to set b_LED=True!\n")
        else:
            stage_frame_rate = float(stage_frame_rate)

        d_timing["stage_frame_rate"] = stage_frame_rate

    if not b_LED:
        try:
            # Set transition times from measured frame times
            pre_frames = np.floor(pre_time_ms * 1e-3 * stage_frame_rate).astype(int)
            stim_frames = np.floor(stim_time_ms * 1e-3 * stage_frame_rate).astype(int)

            # This assumes protocol is visible >=preTime and <preTime+stimTime.
            # Assumption is broken in many places like SpatialNoise where it's <(preTime+stimTime) * 1.011
            frame_times_ms = d_timing["frameTimesMs"]
            n_epochs = len(frame_times_ms)
            actual_onset_times_ms = [
                frame_times_ms[i][pre_frames] for i in range(n_epochs)
            ]
            actual_offset_times_ms = [
                frame_times_ms[i][pre_frames + stim_frames] for i in range(n_epochs)
            ]

        # Exceptions can occur when frame_times_ms are messed up and don't have correct number of frames.
        except Exception as e:
            print(f"Error occurred while getting actual onset/offset times: {e}")
            print(
                "It could be that frame_times_ms do not have the correct number of frames due to some error in frame detection."
            )
            print(
                "Check the frame monitor sample rate! On MEA Rigs, prefer 1k, errors likely with 10k."
            )
            actual_onset_times_ms = []
            actual_offset_times_ms = []

        d_timing["actual_onset_times_ms"] = actual_onset_times_ms
        d_timing["actual_offset_times_ms"] = actual_offset_times_ms

    return d_timing


def get_epochblock_response_query(exp_name: str, block_id: int):
    epochblock_query = get_epochblock_query(exp_name, block_id)
    protocol_query = epochblock_query * schema.Protocol.proj(protocol_name="name")  # type: ignore
    epoch_query = protocol_query * schema.Epoch.proj(
        epoch_parameters="parameters", block_id="parent_id", epoch_id="id"
    )  # type: ignore
    response_query = epoch_query * schema.Response.proj(..., epoch_id="parent_id", response_id="id")  # type: ignore
    return response_query


def get_h5_file(exp_name: str) -> str:
    # First try h5 in config h5 dir
    str_h5_in_config = os.path.join(H5_DIR, f"{exp_name}.h5")
    if os.path.exists(str_h5_in_config):
        return str_h5_in_config

    # Otherwise try path from database
    exp_query = schema.Experiment() & f'exp_name="{exp_name}"'
    str_h5_from_db = exp_query.fetch1("data_file")
    if os.path.exists(str_h5_from_db):
        return str_h5_from_db
    else:
        raise FileNotFoundError(
            f"No h5 file found for experiment {exp_name}.\n"
            + f"Tried {str_h5_in_config} and {str_h5_from_db}"
        )


def get_epochblock_frame_data(
    exp_name: str, block_id: int, str_h5: Optional[str] = None, verbose: bool = True
):
    if str_h5 is None:
        str_h5 = get_h5_file(exp_name)

    if verbose:
        print(f"Loading frame monitor data from {str_h5} ...")

    response_query = get_epochblock_response_query(exp_name, block_id)
    df = response_query.to_pandas().reset_index()

    df_frame = df.query('device_name == "Frame Monitor"')
    df_frame = df_frame.reset_index(drop=True)

    frame_h5paths = df_frame["h5path"].values

    # Collect data
    frame_data = []
    with h5py.File(str_h5, "r") as f:
        for h5path in frame_h5paths:
            trace = f[h5path]["data"]["quantity"]
            frame_data.append(trace)

    frame_data = np.array(frame_data)
    if verbose:
        print(f"Loaded {frame_data.shape} frame_data.\n")

    sample_rates = df_frame["sample_rate"].unique().astype(float)
    if len(sample_rates) == 0 and len(frame_data) == 0:
        print(f"WARNING: Didn't find any frame monitor data and sample rate.")
        print(
            f"If this is for LED stimulus, be sure to set b_LED=True to skip loading this.\n"
        )
        return np.array([]), None
    if len(sample_rates) != 1:
        raise ValueError(
            f"Expected single sample rate for Frame Monitor data, but found {len(sample_rates)}: {sample_rates}"
        )
    sample_rate = sample_rates[0]

    return frame_data, sample_rate


def get_epochblock_amp_data(
    exp_name: str, block_id: int, str_h5: Optional[str] = None, verbose: bool = True
):
    if str_h5 is None:
        str_h5 = get_h5_file(exp_name)

    if verbose:
        print(f"Loading Amp1 data from {str_h5} ...")

    response_query = get_epochblock_response_query(exp_name, block_id)
    df = response_query.to_pandas().reset_index()

    df_amp = df[df["device_name"] == "Amp1"]
    df_amp = df_amp.reset_index(drop=True)

    amp_h5paths = df_amp["h5path"].values

    # Collect data
    amp_data = []
    with h5py.File(str_h5, "r") as f:
        for h5path in amp_h5paths:
            trace = f[h5path]["data"]["quantity"]
            amp_data.append(trace)

    amp_data = np.array(amp_data)
    if verbose:
        print(f"Loaded {amp_data.shape} amp_data.\n")

    sample_rates = df_amp["sample_rate"].unique().astype(float)
    if len(sample_rates) != 1:
        raise ValueError(
            f"Expected single sample rate for Amp1 data, but found {len(sample_rates)}: {sample_rates}"
        )
    sample_rate = sample_rates[0]

    return amp_data, sample_rate
